version: 2.1
# Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
        docker:
          - image: cypress/base:latest
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Build the app
              command: npm run build

workflows:
  run-tests:
    jobs:
      - start-server
      - cypress/run:
          name: Run Cypress Tests
          requires:
            - start-server
          filters:
            branches:
              only: main
          steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Run Cypress tests
                command: npm run test:cypress
            - run:
                name: Run Cypress component tests
                command: npm run test:cypress:component